version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: "portainer"
    network_mode: "bridge"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dockers/portainer/data:/data"
    ports:
      - 9000:9000
    logging:
      options:
          max-size: 50m
  hass:
    image: homeassistant/raspberrypi3-homeassistant:0.94.3
    container_name: "home-assistant"
    network_mode: "host"
    restart: "unless-stopped"
    depends_on:
      - samba
    volumes:
      - "/home/$USER/share/ha:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8123:8123
    devices:
      - "/dev/mem"
    cap_add:
      - SYS_RAWIO
    logging:
      options:
        max-size: 50m
    privileged: true
        
  samba:
    image: dperson/samba:rpi
    container_name: "samba"
    network_mode: "host"
    restart: "unless-stopped"
    command: -u "pi;${DOCKER_SAMBA_PI_PASSWORD}" -s "share;/share;no;no;no;pi;pi;pi"
    volumes:
      - /home/pi/share:/share
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    logging:
      options:
        max-size: 50m

  cloudflare-ddns:
    image: "oznu/cloudflare-ddns:armhf"
    container_name: "cloudflare-ddns"
    restart: "unless-stopped"
    environment:
      - EMAIL=${DOCKER_CF_EMAIL}
      - API_KEY=${DOCKER_CF_API_KEY}
      - ZONE=${DOCKER_CF_ZONE}
      - SUBDOMAIN=${DOCKER_CF_DOMAIN}
      - PROXIED=false
    logging:
      options:
          max-size: 50m
  letsencrypt:
    image: linuxserver/letsencrypt:latest
    container_name: letsencrypt
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/$USER/share/letsencrypt/config:/config
    environment:
    - PGID=1000
    - PUID=1000
    - EMAIL=${DOCKER_LE_EMAIL}
    - URL=${DOCKER_LE_URL}
    - SUBDOMAINS=${DOCKER_LE_SUBDOMAINS}
    - ONLY_SUBDOMAINS=true
    - VALIDATION=dns
    - DNSPLUGIN=cloudflare
    - TZ=Europe/London
    ports:
    - "80:80"
    - "443:443"

  unifi-controller:
    image: linuxserver/unifi-controller:arm32v7-5.10.24-ls20
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "/home/$USER/share/unifi-controller:/config"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
    